// <auto-generated />
using System;
using API_Web.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Web.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20241114152517_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_Web.Models.Danh_Muc", b =>
                {
                    b.Property<int>("Id_DM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_DM"));

                    b.Property<string>("Ten_DM")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_DM");

                    b.ToTable("Danh_Muc");
                });

            modelBuilder.Entity("API_Web.Models.Khoa_Hoc", b =>
                {
                    b.Property<Guid>("Id_KH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Chuong")
                        .HasColumnType("int");

                    b.Property<double>("Gia")
                        .HasColumnType("float");

                    b.Property<byte>("GiamGia")
                        .HasColumnType("tinyint");

                    b.Property<int?>("Id_DM")
                        .HasColumnType("int");

                    b.Property<string>("Mieu_ta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten_Khoa_Hoc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Tong_Thoi_Gian")
                        .HasColumnType("int");

                    b.Property<string>("Url_Img")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_KH");

                    b.HasIndex("Id_DM");

                    b.ToTable("Khoa_Hoc");
                });

            modelBuilder.Entity("API_Web.Models.Khoa_Hoc", b =>
                {
                    b.HasOne("API_Web.Models.Danh_Muc", "DanhMuc")
                        .WithMany("Khoa_Hocs")
                        .HasForeignKey("Id_DM");

                    b.Navigation("DanhMuc");
                });

            modelBuilder.Entity("API_Web.Models.Danh_Muc", b =>
                {
                    b.Navigation("Khoa_Hocs");
                });
#pragma warning restore 612, 618
        }
    }
}
